name: base
channels:
  - pytorch
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0=py39hecd8cb5_1
  - aiohttp=3.8.1=py39hca72f7f_1
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anaconda=2022.05=py39_0
  - anaconda-client=1.9.0=py39hecd8cb5_0
  - anaconda-navigator=2.1.4=py39hecd8cb5_0
  - anaconda-project=0.10.2=pyhd3eb1b0_0
  - anyio=3.5.0=py39hecd8cb5_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - applaunchservices=0.2.1=pyhd3eb1b0_0
  - appnope=0.1.2=py39hecd8cb5_1001
  - appscript=1.1.2=py39h9ed2024_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39hca72f7f_0
  - arrow=1.2.2=pyhd3eb1b0_0
  - astroid=2.6.6=py39hecd8cb5_0
  - astropy=5.0.4=py39h67323c0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - automat=20.2.0=py_0
  - autopep8=1.6.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
  - backports.tempfile=1.0=pyhd3eb1b0_1
  - backports.weakref=1.0.post1=py_1
  - bcrypt=3.2.0=py39h9ed2024_0
  - beautifulsoup4=4.11.1=py39hecd8cb5_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - bitarray=2.4.1=py39hca72f7f_0
  - bkcharts=0.2=py39hecd8cb5_0
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.0=h2842e9f_0
  - boto3=1.21.32=pyhd3eb1b0_0
  - botocore=1.24.32=pyhd3eb1b0_0
  - bottleneck=1.3.4=py39h67323c0_0
  - brotli=1.0.9=hb1e8313_2
  - brotlipy=0.7.0=py39h9ed2024_1003
  - brunsli=0.1=h23ab428_0
  - bzip2=1.0.8=h1de35cc_0
  - c-ares=1.18.1=hca72f7f_0
  - ca-certificates=2022.3.29=hecd8cb5_1
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2021.10.8=py39hecd8cb5_2
  - cffi=1.15.0=py39hc55c11b_1
  - cfitsio=3.470=hee0f690_6
  - chardet=4.0.0=py39hecd8cb5_1003
  - charls=2.2.0=h23ab428_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py39hecd8cb5_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - clyent=1.2.2=py39hecd8cb5_1
  - colorama=0.4.4=pyhd3eb1b0_0
  - colorcet=2.0.6=pyhd3eb1b0_0
  - conda=22.9.0=py39hecd8cb5_0
  - conda-build=3.21.8=py39hecd8cb5_2
  - conda-content-trust=0.1.1=pyhd3eb1b0_0
  - conda-env=2.6.0=1
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - conda-package-handling=1.8.1=py39hca72f7f_0
  - conda-repo-cli=1.0.4=pyhd3eb1b0_0
  - conda-token=0.3.0=pyhd3eb1b0_0
  - conda-verify=3.4.2=py_1
  - constantly=15.1.0=pyh2b92418_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=3.4.8=py39h2fd3fbb_0
  - cssselect=1.1.0=pyhd3eb1b0_0
  - curl=7.82.0=hca72f7f_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.11.0=py39h9ed2024_0
  - daal4py=2021.5.0=py39h24a4e90_0
  - dal=2021.5.0=hecd8cb5_782
  - dask=2022.2.1=pyhd3eb1b0_0
  - dask-core=2022.2.1=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - datashader=0.13.0=pyhd3eb1b0_1
  - datashape=0.5.4=py39hecd8cb5_1
  - debugpy=1.5.1=py39he9d5cce_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - distributed=2022.2.1=pyhd3eb1b0_0
  - docutils=0.17.1=py39hecd8cb5_1
  - entrypoints=0.4=py39hecd8cb5_0
  - et_xmlfile=1.1.0=py39hecd8cb5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.3=h0a44026_0
  - filelock=3.6.0=pyhd3eb1b0_0
  - flake8=3.9.2=pyhd3eb1b0_0
  - flask=1.1.2=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=hd8bbffd_0
  - frozenlist=1.2.0=py39hca72f7f_0
  - fsspec=2022.2.0=pyhd3eb1b0_0
  - future=0.18.2=py39hecd8cb5_1
  - gensim=4.1.2=py39he9d5cce_0
  - gettext=0.21.0=h7535e17_0
  - giflib=5.2.1=haf1e3a3_0
  - glob2=0.7=pyhd3eb1b0_0
  - gmp=6.2.1=h23ab428_2
  - gmpy2=2.1.2=py39hd5de756_0
  - gnutls=3.6.15=hed9c0bf_0
  - google-api-core=1.25.1=pyhd3eb1b0_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-cloud-core=1.7.1=pyhd3eb1b0_0
  - google-cloud-storage=1.31.0=py_0
  - google-crc32c=1.1.2=py39h9ed2024_0
  - google-resumable-media=1.3.1=pyhd3eb1b0_1
  - googleapis-common-protos=1.53.0=py39hecd8cb5_0
  - greenlet=1.1.1=py39h23ab428_0
  - h5py=3.6.0=py39h4a1dd59_0
  - hdf5=1.10.6=hdbbcd12_0
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holoviews=1.14.8=pyhd3eb1b0_0
  - hvplot=0.7.3=pyhd3eb1b0_1
  - hyperlink=21.0.0=pyhd3eb1b0_0
  - icu=58.2=h0a44026_3
  - idna=3.3=pyhd3eb1b0_0
  - imagecodecs=2021.8.26=py39ha952a84_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - imagesize=1.3.0=pyhd3eb1b0_0
  - importlib-metadata=4.11.3=py39hecd8cb5_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - incremental=21.3.0=pyhd3eb1b0_0
  - inflection=0.5.1=py39hecd8cb5_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intake=0.6.5=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=hecd8cb5_3538
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.9.1=py39hecd8cb5_0
  - ipython=8.2.0=py39hecd8cb5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - itemadapter=0.3.0=pyhd3eb1b0_0
  - itemloaders=1.0.4=pyhd3eb1b0_1
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jdcal=1.4.1=pyhd3eb1b0_0
  - jedi=0.18.1=py39hecd8cb5_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - jmespath=0.10.0=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=hca72f7f_0
  - jq=1.6=h9ed2024_1000
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.4.0=py39hecd8cb5_0
  - jupyter=1.0.0=py39hecd8cb5_7
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.9.2=py39hecd8cb5_0
  - jupyter_server=1.13.5=pyhd3eb1b0_0
  - jupyterlab=3.3.2=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.3=pyhd3eb1b0_1
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - jxrlib=1.1=haf1e3a3_2
  - keyring=23.4.0=py39hecd8cb5_0
  - kiwisolver=1.3.2=py39he9d5cce_0
  - krb5=1.19.2=hcd88c3b_0
  - lame=3.100=h1de35cc_0
  - lazy-object-proxy=1.6.0=py39h9ed2024_0
  - lcms2=2.12=hf1fd2bf_0
  - lerc=3.0=he9d5cce_0
  - libaec=1.0.4=hb1e8313_1
  - libarchive=3.4.2=haa3ed63_0
  - libcrc32c=1.1.1=hb1e8313_2
  - libcurl=7.82.0=h6dfd666_0
  - libcxx=12.0.0=h2f01273_0
  - libdeflate=1.8=h9ed2024_5
  - libedit=3.1.20210910=hca72f7f_0
  - libev=4.33=h9ed2024_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=hca72f7f_2
  - libidn2=2.3.2=h9ed2024_0
  - liblief=0.11.5=he9d5cce_1
  - libllvm11=11.1.0=h46f1229_1
  - libnghttp2=1.46.0=ha29bfda_0
  - libpng=1.6.37=ha441bb4_0
  - libprotobuf=3.19.1=h8346a28_0
  - libsodium=1.0.18=h1de35cc_0
  - libspatialindex=1.9.3=h23ab428_0
  - libssh2=1.10.0=h0a4fc7d_0
  - libtasn1=4.16.0=h9ed2024_0
  - libtiff=4.2.0=h87d7836_0
  - libunistring=0.9.10=h9ed2024_0
  - libwebp=1.2.2=h56c3ce4_0
  - libwebp-base=1.2.2=hca72f7f_0
  - libxml2=2.9.12=hcdb78fc_0
  - libxslt=1.1.34=h83b36ba_0
  - libzopfli=1.0.3=hb1e8313_0
  - llvm-openmp=12.0.0=h0dcd299_1
  - llvmlite=0.38.0=py39h8346a28_0
  - locket=0.2.1=py39hecd8cb5_2
  - lxml=4.8.0=py39h65b224f_0
  - lz4-c=1.9.3=h23ab428_1
  - lzo=2.10=haf1e3a3_2
  - markdown=3.3.4=py39hecd8cb5_0
  - markupsafe=2.0.1=py39h9ed2024_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.6.1=py39hecd8cb5_1
  - mistune=0.8.4=py39h9ed2024_1000
  - mkl=2021.4.0=hecd8cb5_637
  - mkl-service=2.4.0=py39h9ed2024_0
  - mkl_fft=1.3.1=py39h4ab4a9b_0
  - mkl_random=1.2.2=py39hb2f4e1b_0
  - mock=4.0.3=pyhd3eb1b0_0
  - mpc=1.1.0=h6ef4df4_1
  - mpfr=4.0.2=h9066e36_1
  - mpi=1.0=mpich
  - mpich=3.3.2=hc856adb_0
  - mpmath=1.2.1=py39hecd8cb5_0
  - msgpack-python=1.0.2=py39hf7b0b51_1
  - multidict=5.2.0=py39hca72f7f_2
  - multipledispatch=0.6.0=py39hecd8cb5_0
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py39hecd8cb5_1
  - navigator-updater=0.2.1=py39_1
  - nbclassic=0.3.5=pyhd3eb1b0_0
  - nbclient=0.5.13=py39hecd8cb5_0
  - nbconvert=6.4.4=py39hecd8cb5_0
  - nbformat=5.3.0=py39hecd8cb5_0
  - ncurses=6.3=hca72f7f_2
  - nest-asyncio=1.5.5=py39hecd8cb5_0
  - nettle=3.7.3=h230ac6f_1
  - networkx=2.7.1=pyhd3eb1b0_0
  - nltk=3.7=pyhd3eb1b0_0
  - nose=1.3.7=pyhd3eb1b0_1008
  - notebook=6.4.8=py39hecd8cb5_0
  - numba=0.55.1=py39hae1ba45_0
  - numexpr=2.8.1=py39h2e5f0a9_0
  - numpydoc=1.2=pyhd3eb1b0_0
  - olefile=0.46=pyhd3eb1b0_0
  - oniguruma=6.9.7.1=h9ed2024_0
  - openh264=2.1.1=h8346a28_0
  - openjpeg=2.4.0=h66ea3da_0
  - openpyxl=3.0.9=pyhd3eb1b0_0
  - openssl=1.1.1n=hca72f7f_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.2=py39he9d5cce_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - panel=0.13.0=py39hecd8cb5_0
  - param=1.12.0=pyhd3eb1b0_0
  - parsel=1.6.0=py39hecd8cb5_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pathspec=0.7.0=py_0
  - patsy=0.5.2=py39hecd8cb5_1
  - pep8=1.7.1=py39hecd8cb5_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py39hde71d04_0
  - pkginfo=1.8.2=pyhd3eb1b0_0
  - plotly=5.6.0=pyhd3eb1b0_0
  - pluggy=1.0.0=py39hecd8cb5_1
  - poyo=0.5.0=pyhd3eb1b0_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - protego=0.1.16=py_0
  - protobuf=3.19.1=py39he9d5cce_0
  - psutil=5.8.0=py39h9ed2024_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py=1.11.0=pyhd3eb1b0_0
  - py-lief=0.11.5=py39he9d5cce_1
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pycosat=0.6.3=py39h9ed2024_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyct=0.4.6=py39hecd8cb5_0
  - pycurl=7.44.1=py39hbcfaee0_1
  - pydispatcher=2.0.5=py39hecd8cb5_2
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyerfa=2.0.0=py39h9ed2024_0
  - pyflakes=2.3.1=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyhamcrest=2.0.2=pyhd3eb1b0_2
  - pyjwt=2.1.0=py39hecd8cb5_0
  - pylint=2.9.6=py39hecd8cb5_1
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pyodbc=4.0.32=py39he9d5cce_1
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h23ab428_6
  - pyrsistent=0.18.0=py39hca72f7f_0
  - pysocks=1.7.1=py39hecd8cb5_0
  - pytables=3.6.1=py39h648f197_1
  - pytest=7.1.1=py39hecd8cb5_0
  - python=3.9.12=hdfd78df_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python-lsp-black=1.0.0=pyhd3eb1b0_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.2.4=pyhd3eb1b0_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-snappy=0.6.0=py39h23ab428_3
  - python.app=3=py39hca72f7f_0
  - pytorch=1.12.1=py3.9_0
  - pytz=2021.3=pyhd3eb1b0_0
  - pyviz_comms=2.0.2=pyhd3eb1b0_0
  - pywavelets=1.3.0=py39hca72f7f_0
  - pyyaml=6.0=py39hca72f7f_1
  - pyzmq=22.3.0=py39he9d5cce_2
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.1.10=pyhd3eb1b0_0
  - qt=5.9.7=h468cd18_1
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.3.0=pyhd3eb1b0_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - queuelib=1.5.0=py39hecd8cb5_0
  - readline=8.1.2=hca72f7f_1
  - regex=2022.3.15=py39hca72f7f_0
  - requests=2.27.1=pyhd3eb1b0_0
  - requests-file=1.5.1=pyhd3eb1b0_0
  - ripgrep=12.1.1=0
  - rope=0.22.0=pyhd3eb1b0_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - rtree=0.9.7=py39hecd8cb5_1
  - ruamel_yaml=0.15.100=py39h9ed2024_0
  - s3transfer=0.5.0=pyhd3eb1b0_0
  - scikit-image=0.19.2=py39hae1ba45_0
  - scikit-learn=1.0.2=py39hae1ba45_1
  - scikit-learn-intelex=2021.5.0=py39hecd8cb5_0
  - scipy=1.7.3=py39h8c7af03_0
  - scrapy=2.6.1=py39hecd8cb5_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - service_identity=18.1.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py39hecd8cb5_0
  - sip=4.19.13=py39h23ab428_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.1.0=pyhd3eb1b0_0
  - snappy=1.1.9=he9d5cce_0
  - sniffio=1.2.0=py39hecd8cb5_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcollections=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sphinx=4.4.0=pyhd3eb1b0_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.1.5=py39hecd8cb5_1
  - spyder-kernels=2.1.3=py39hecd8cb5_0
  - sqlalchemy=1.4.32=py39hca72f7f_0
  - sqlite=3.38.2=h707629a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.13.2=py39hca72f7f_0
  - sympy=1.10.1=py39hecd8cb5_0
  - tabulate=0.8.9=py39hecd8cb5_0
  - tbb=2021.5.0=haf03e11_0
  - tbb4py=2021.5.0=py39haf03e11_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=8.0.1=py39hecd8cb5_0
  - terminado=0.13.1=py39hecd8cb5_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tinycss=0.4=pyhd3eb1b0_1002
  - tk=8.6.11=h7bc2e8c_0
  - tldextract=3.2.0=pyhd3eb1b0_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=1.2.2=pyhd3eb1b0_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchvision=0.13.1=py39_cpu
  - tornado=6.1=py39h9ed2024_0
  - tqdm=4.64.0=py39hecd8cb5_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - twisted=22.2.0=py39hca72f7f_0
  - typed-ast=1.4.3=py39h9ed2024_1
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - ujson=5.1.0=py39he9d5cce_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - unixodbc=2.3.9=haf1e3a3_0
  - urllib3=1.26.9=py39hecd8cb5_0
  - w3lib=1.21.0=pyhd3eb1b0_0
  - watchdog=2.1.6=py39h999c104_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39hecd8cb5_1
  - werkzeug=2.0.3=pyhd3eb1b0_0
  - wget=1.21.3=h6dfd666_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py39hecd8cb5_0
  - wrapt=1.12.1=py39h9ed2024_1
  - wurlitzer=3.0.2=py39hecd8cb5_0
  - xarray=0.20.1=pyhd3eb1b0_1
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xlsxwriter=3.0.3=pyhd3eb1b0_0
  - xlwings=0.24.9=py39hecd8cb5_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - yarl=1.6.3=py39h9ed2024_0
  - zeromq=4.3.4=h23ab428_0
  - zfp=0.5.5=he9d5cce_6
  - zict=2.0.0=pyhd3eb1b0_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.12=h4dc903c_2
  - zope=1.0=py39hecd8cb5_1
  - zope.interface=5.4.0=py39h9ed2024_0
  - zstd=1.4.9=h322a384_0
  - pip:
    - absl-py==1.2.0
    - akshare==1.8.22
    - alembic==1.8.1
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - attrdict==2.0.1
    - backtrader==1.9.76.123
    - backtrader-plotting==2.0.0
    - bidict==0.22.0
    - bokeh==2.3.3
    - bs4==0.0.1
    - cattrs==22.2.0
    - cfscrape==2.1.1
    - chex==0.1.5
    - coloredlogs==14.0
    - commonmark==0.9.1
    - comtypes==1.1.14
    - contourpy==1.0.6
    - croniter==1.3.8
    - cvxpy==1.2.2
    - cython==0.29.32
    - dagster==1.1.20
    - databricks-cli==0.17.4
    - ddddocr==1.4.7
    - deprecation==2.1.0
    - diffusers==0.5.1
    - dill==0.3.6
    - dm-pix==0.3.4
    - dm-tree==0.1.7
    - docker==6.0.1
    - docopt==0.6.2
    - docstring-parser==0.15
    - easyquotation==0.7.5
    - easytrader==0.23.0
    - easyutils==0.1.7
    - ecos==2.0.10
    - etils==0.8.0
    - exceptiongroup==1.0.4
    - fastapi==0.88.0
    - fire==0.4.0
    - flatbuffers==22.9.24
    - flax==0.6.1
    - fvcore==0.1.5.post20220512
    - gast==0.4.0
    - gin-config==0.5.0
    - gitdb==4.0.10
    - gitpython==3.1.29
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.47.2
    - grpcio-health-checking==1.43.0
    - gunicorn==20.1.0
    - html5lib==1.1
    - huggingface-hub==0.10.1
    - humanfriendly==10.0
    - hyperopt==0.1.1
    - img2pdf==0.4.1
    - importlib-resources==5.10.0
    - imutils==0.5.4
    - invisible-watermark==0.1.5
    - iopath==0.1.10
    - itchat==1.2.32
    - jax==0.3.23
    - jaxlib==0.3.22
    - jqdatasdk==1.8.11
    - jsonpath==0.82
    - jsonpickle==1.5.2
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.6
    - lightgbm==3.3.3
    - logbook==1.5.3
    - loguru==0.6.0
    - mako==1.2.4
    - markdown2==2.4.6
    - matplotlib==3.6.2
    - mediapy==1.1.0
    - mlflow==2.0.1
    - mpl-finance==0.10.1
    - mplfinance==0.12.9b7
    - multitasking==0.0.11
    - munch==2.5.0
    - numpy==1.21.6
    - oauthlib==3.2.1
    - onnx==1.12.0
    - onnxruntime==1.12.1
    - opencv-python==4.6.0.66
    - opencv-python-headless==4.6.0.66
    - opt-einsum==3.3.0
    - optax==0.1.3
    - osqp==0.6.2.post8
    - pandas-datareader==0.10.0
    - pendulum==2.1.2
    - pikepdf==6.2.4
    - pip==23.0.1
    - pipreqs==0.4.11
    - ply==3.11
    - portalocker==2.6.0
    - progressbar==2.5
    - py-cpuinfo==9.0.0
    - py-mini-racer==0.6.0
    - pyarrow==10.0.1
    - pydantic==1.10.2
    - pymongo==3.7.2
    - pymysql==1.0.2
    - pypinyin==0.47.1
    - pypng==0.20220715.0
    - pyqlib==0.7.2.99
    - pyqrcode==1.2.1
    - pyquery==1.4.3
    - python-dotenv==0.21.0
    - python-engineio==4.3.4
    - python-redis-lock==4.0.0
    - python-socketio==5.7.2
    - pytorch3d==0.7.1
    - pytzdata==2020.1
    - pywinauto==0.6.6
    - qdldl==0.1.5.post2
    - qlib==0.0.2.dev20
    - quantstats==0.0.59
    - querystring-parser==1.2.4
    - rawpy==0.17.2
    - redis==4.4.0
    - requests-cache==0.9.7
    - requests-oauthlib==1.3.1
    - rich==12.6.0
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.7
    - sacred==0.8.2
    - schedule==1.1.0
    - scs==3.2.2
    - shap==0.41.0
    - simplejson==3.18.0
    - slicer==0.0.7
    - smmap==5.0.0
    - sqlparse==0.4.3
    - starlette==0.22.0
    - ta-lib==0.4.25
    - tablib==3.2.1
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.10.0
    - tensorflow-estimator==2.10.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - termcolor==2.0.1
    - tf-slim==1.1.0
    - thriftpy2==0.4.16
    - tokenizers==0.12.1
    - toposort==1.10
    - transformers==4.19.2
    - tushare==1.2.86
    - universal-pathlib==0.0.21
    - url-normalize==1.4.3
    - websocket-client==0.57.0
    - wxpy==0.3.9.8
    - wxpython==4.2.0
    - yacs==0.1.8
    - yarg==0.1.9
    - yfinance==0.1.87
prefix: /usr/local/anaconda3
